import Head from "next/head";
import { Navbar } from "@/components/Navbar/Navbar";
import { Footer } from "@/components/Footer/Footer";
import { Hero } from "@/components/Hero/Hero";
import { groq } from "next-sanity";
import type { SanityDocument } from "@sanity/client";
import { client } from "../lib/sanity.client";

const query = groq`*[_type == "movie" && defined(slug.current)]{
  _id,
  title, 
  slug
}`;


export default function Home({ data }: { data: SanityDocument[] }) {
  console.log({data})
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Hero />
        <Footer />
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const data = await client.fetch(query);

  return { props: { data } };
};